### PR TITLE
S3 upload

### PR DESCRIPTION
**Pull request by alanshaw**
- Uploads built sitemap files to S3
- Adds deploy docs

screen shot 2016-08-18 at 21 29 13

### CODE REVIEW

**Comment by Danwhy** [comment]
:+1: @SimonLab?

**Comment by Danwhy** [comment]
:+1: @SimonLab?

**Comment by SimonLab** [comment]
LGTM

**Comment by nelsonic** [comment]
@alanshaw code looks good. could we make Travis happy before merging?

**Comment by nelsonic** [comment]
Ok... 😜

**Comment by SimonLab** [comment]
Sorry @nelsonic, @alanshaw explain that the other PR was adding the CI

**Comment by alanshaw** [comment]
@nelsonic travis was only failing because I authored this PR before the CI hookups PR so this branch doesn't have a `.travis.yml` and it thinks it is ruby or something :P

**Pull request merged**
